
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('fakeHints').del()
    .then(function () {
      // Inserts seed entries
      return knex('fakeHints').insert([
        { id: 1, fakeHint: 'There’s no information about Aliens today.  How’s your day going?' },
        { id: 2, fakeHint: 'Cherie from accounting stole my sandwich again.  Damnit Cherie.' },
        { id: 3, fakeHint: 'ALIENS HAVE OVERTHROWN THE GOVERNMENT. FLEE!\nHahahaha gotcha.'},
        { id: 4, fakeHint: 'The forecast for your city is… terrible.  You should probably move.' },
        { id: 5, fakeHint: 'Bureau of Space Stuff? More like Bureau of Stupid Stuff, am I right?\nDamnit Frank, I told you interns are not allowed to communicate to agents in the field.'},
        { id: 6, fakeHint: 'BOSS is changing it’s image!  We are hereby known as BASS.  Slap it.' },
        { id: 7, fakeHint: 'BOSS just ended employer-sponsored health insurance. Maybe the aliens would be better bosses?' },
        { id: 8, fakeHint: 'I for one welcome our new alien overlords.' },
        { id: 9, fakeHint: 'IT’S A TRAP!' },
        { id: 10, fakeHint: 'A recent lawsuit from Bruce Springsteen has required BOSS to change our name. Do you have any thoughts?' },
        { id: 11, fakeHint: 'A truck on a nearby highway overturned, gently spilling baby lambs everywhere!  It’s the cuddliest accident ever!' },
        { id: 12, fakeHint: 'When I was a little boy I wanted to play the flute.  Toot toot!' },
        { id: 13, fakeHint: 'Aww man I just spilt my coffee.' },
        { id: 14, fakeHint: 'Test test 1 2 3.  Does this thing work?' },
        { id: 15, fakeHint: 'We recently had a satellite go down, so no new info until Elon can pull himself together.' },
        { id: 16, fakeHint: 'Do you remember that one episode where that guy did that thing?  That was the best!' },
        { id: 17, fakeHint: 'I reckon I could be a famous singer.  What do you think? LALALALALALALALALALA!' },
        { id: 18, fakeHint: 'Who would win in a fight, a gorilla or a bear?' },
        { id: 19, fakeHint: 'Look, I never really wanted to be a space agency communications director. When I was young I wanted to be the Hamburgler.' },
        { id: 20, fakeHint: 'Would you rather fight a bear sized duck, or 100 duck sized bears?' },
        { id: 21, fakeHint: 'What\'s that sound?' },
        { id: 22, fakeHint: 'That seems familiar?!' },
        { id: 23, fakeHint: 'Movies?' },
        { id: 24, fakeHint: 'Are you hungry?' },
        { id: 25, fakeHint: 'Thirsty much?' },
        { id: 26, fakeHint: 'Ohhhh smelly!' },
        { id: 27, fakeHint: 'What are you looking at?' },
        { id: 28, fakeHint: 'I know that quote!' },
        { id: 29, fakeHint: 'What a weird word.' },
        { id: 30, fakeHint: 'Why are you doing that?' },
        { id: 31, fakeHint: 'Think - snacks.' },
        { id: 32, fakeHint: 'Would you eat that?' },
        { id: 33, fakeHint: 'It\'s getting hot in here!' },
        { id: 34, fakeHint: 'Can they see?' },
        { id: 35, fakeHint: 'Why are you talking alot?' },
        { id: 36, fakeHint: 'You\'re not making sense.' },
        { id: 37, fakeHint: 'Who\'s itchy?' },
        { id: 38, fakeHint: 'Who are you?' },
        { id: 39, fakeHint: 'Holdiay mode?' },
        { id: 40, fakeHint: 'I\'ve never used that word!' },
        { id: 41, fakeHint: 'Do you even talk to them anymore?' },
        { id: 42, fakeHint: 'You\'ve never been there!' },
        { id: 43, fakeHint: 'Slow down!' },
        { id: 44, fakeHint: 'Do you always talk that way?' },
        { id: 45, fakeHint: 'You\'d never do that?!' },
        { id: 46, fakeHint: 'Why are you drinking so much?' },
        { id: 47, fakeHint: 'Do you like comics?' },
        { id: 48, fakeHint: 'Have you ever done that?' },
        { id: 49, fakeHint: 'Think - music.' },
        { id: 50, fakeHint: 'Dreaming?' },
        { id: 51, fakeHint: 'Speed up!' },
        { id: 52, fakeHint: 'You aren\'t your usual self?' },
        { id: 53, fakeHint: 'Is that an interest of yours?' },
        { id: 54, fakeHint: 'Think - short term.' },
        { id: 55, fakeHint: 'Do you watch movies?' },
        { id: 56, fakeHint: 'Musical talent?' },
        { id: 57, fakeHint: 'Who\'s touchy?' },
        { id: 58, fakeHint: 'That doesn\'t seem normal' },
        { id: 59, fakeHint: 'Smells like?' },
        { id: 60, fakeHint: 'Do you even talk?' },
        { id: 61, fakeHint: 'Is it cold?' },
        { id: 62, fakeHint: 'Getting fidgety?' },
        { id: 63, fakeHint: 'What\'s that tv show?' },
        { id: 64, fakeHint: 'It\'s not normal!' },
        { id: 65, fakeHint: 'Think - drinks.' }
      ])
    })
}
